// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bot-status-card/AccessibilityFirst.tsx": () => import("../components/mockups/bot-status-card/AccessibilityFirst.tsx"),
  "./components/mockups/bot-status-card/HierarchyFirst.tsx": () => import("../components/mockups/bot-status-card/HierarchyFirst.tsx"),
  "./components/mockups/bot-status-card/InteractionFirst.tsx": () => import("../components/mockups/bot-status-card/InteractionFirst.tsx")
};
